openapi: 3.0.0
info: { title: Xainik API, version: "0.1" }
paths:
  /api/events: { get: {}, post: {} }
  /api/speakers: { get: {}, post: {} }
  /api/bookings: { post: {} }
  /api/donations/create-order: { post: {} }
  /api/donations/verify: { post: {} }
  /api/donations/receipt: { get: {} }