name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - run: pnpm i
      - run: pnpm prisma generate
      - run: pnpm tsx scripts/spec-check.ts
      - run: pnpm tsx scripts/find-dead.ts
      - run: pnpm tsc --noEmit
      - run: pnpm lint --if-present
      - run: pnpm test --if-present
